package server

// Hand-written OpenAPI 3 document for the /2 (X API v2 compatible) surface. Unlike
// /v1 (generated by reflection over Go response types, which always wraps success
// in {data}), the v2 body is {data, includes, meta, errors} with dynamic field
// selection, so its schema is authored by hand and served separately at
// /openapi-v2.json. Keeping it out of buildSpec leaves docs_test's v1 operation
// count untouched.

import (
	"encoding/json"
	"log"
	"net/http"

	"x-rest-api/internal/version"
)

// v2SpecJSON is the marshaled v2 document, built once at startup.
var v2SpecJSON = mustMarshalV2()

// mustMarshalV2 marshals the v2 document, falling back to a minimal stub on error.
func mustMarshalV2() []byte {
	b, err := json.Marshal(v2Document())
	if err != nil {
		log.Printf("openapi v2: marshal spec: %v", err)
		return []byte(`{"openapi":"3.0.3","info":{"title":"x-rest-api v2","version":"` + version.Version + `"},"paths":{}}`)
	}
	return b
}

// openapiV2JSON serves the v2 OpenAPI document (no auth).
func (s *Server) openapiV2JSON(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("content-type", "application/json; charset=utf-8")
	_, _ = w.Write(v2SpecJSON)
}

// v2FieldParams are the shared field-selection query parameters referenced by
// every v2 operation.
func v2FieldParams() []any {
	names := []string{"tweet.fields", "user.fields", "media.fields", "poll.fields", "place.fields", "expansions"}
	out := make([]any, 0, len(names))
	for _, n := range names {
		out = append(out, map[string]any{
			"name": n, "in": "query", "required": false,
			"description": "Comma-separated " + n + " selection, matching X API v2.",
			"schema":      map[string]any{"type": "string"},
		})
	}
	return out
}

// v2PathParam builds a required path parameter.
func v2PathParam(name, desc string) map[string]any {
	return map[string]any{
		"name": name, "in": "path", "required": true,
		"description": desc, "schema": map[string]any{"type": "string"},
	}
}

// v2QueryParam builds an optional query parameter.
func v2QueryParam(name, desc string) map[string]any {
	return map[string]any{
		"name": name, "in": "query", "required": false,
		"description": desc, "schema": map[string]any{"type": "string"},
	}
}

// v2EnvelopeResponse is the shared 200 response returning the envelope schema.
func v2EnvelopeResponse() map[string]any {
	return map[string]any{
		"description": "X API v2 response envelope",
		"content": map[string]any{
			"application/json": map[string]any{
				"schema": map[string]any{"$ref": "#/components/schemas/Envelope"},
			},
		},
	}
}

// v2Op builds one GET operation with the shared field params plus any extras,
// secured by bearerAuth and returning the envelope schema.
func v2Op(summary string, extra ...map[string]any) map[string]any {
	params := v2FieldParams()
	for _, p := range extra {
		params = append(params, p)
	}
	return map[string]any{
		"summary":    summary,
		"tags":       []string{"x-api-v2"},
		"security":   []any{map[string]any{"bearerAuth": []any{}}},
		"parameters": params,
		"responses":  map[string]any{"200": v2EnvelopeResponse()},
	}
}

// v2WriteOp builds a write operation (POST/DELETE), optionally with a JSON body
// and path parameters, secured by bearerAuth and returning the envelope schema.
func v2WriteOp(summary string, hasBody bool, params ...map[string]any) map[string]any {
	op := map[string]any{
		"summary":   summary,
		"tags":      []string{"x-api-v2"},
		"security":  []any{map[string]any{"bearerAuth": []any{}}},
		"responses": map[string]any{"200": v2EnvelopeResponse()},
	}
	if len(params) > 0 {
		op["parameters"] = params
	}
	if hasBody {
		op["requestBody"] = map[string]any{
			"required": true,
			"content": map[string]any{
				"application/json": map[string]any{"schema": map[string]any{"type": "object"}},
			},
		}
	}
	return op
}

// v2Document builds the full v2 OpenAPI 3 document.
func v2Document() map[string]any {
	idParam := v2PathParam("id", "Numeric user or tweet id.")
	return map[string]any{
		"openapi": "3.0.3",
		"info": map[string]any{
			"title":       "x-rest-api (X API v2 compatible)",
			"version":     version.Version,
			"description": "A selective, X API v2 compatible read surface over x.com. Requests and responses mirror the official v2 shape.",
		},
		"paths":      v2Paths(idParam),
		"components": v2Components(),
	}
}

// v2Paths builds the path map for the v2 read surface.
func v2Paths(idParam map[string]any) map[string]any {
	userParam := v2PathParam("username", "The user's handle, without @.")
	return map[string]any{
		"/2/users/by/username/{username}": map[string]any{"get": v2Op("Look up a user by username", userParam)},
		"/2/users/{id}":                   map[string]any{"get": v2Op("Look up a user by id", idParam)},
		"/2/users":                        map[string]any{"get": v2Op("Look up users by id", v2QueryParam("ids", "Comma-separated user ids (required)."))},
		"/2/users/by":                     map[string]any{"get": v2Op("Look up users by username", v2QueryParam("usernames", "Comma-separated usernames (required)."))},
		"/2/users/{id}/tweets": map[string]any{"get": v2Op("A user's recent tweets", idParam,
			v2QueryParam("max_results", "Page size, 5-100 (default 10)."),
			v2QueryParam("pagination_token", "Cursor from a previous meta.next_token."))},
		"/2/tweets/{id}": map[string]any{
			"get":    v2Op("Look up a tweet by id", idParam),
			"delete": v2WriteOp("Delete a tweet", false, idParam),
		},
		"/2/tweets": map[string]any{
			"get":  v2Op("Look up tweets by id", v2QueryParam("ids", "Comma-separated tweet ids (required).")),
			"post": v2WriteOp("Create a tweet", true),
		},
		"/2/tweets/search/recent": map[string]any{"get": v2Op("Recent tweet search",
			v2QueryParam("query", "Search query (required)."),
			v2QueryParam("max_results", "Page size, 5-100 (default 10)."),
			v2QueryParam("next_token", "Cursor from a previous meta.next_token."))},
		"/2/users/{id}/likes":                      map[string]any{"post": v2WriteOp("Like a tweet", true, idParam)},
		"/2/users/{id}/likes/{tweet_id}":           map[string]any{"delete": v2WriteOp("Unlike a tweet", false, idParam, v2PathParam("tweet_id", "The liked tweet id."))},
		"/2/users/{id}/retweets":                   map[string]any{"post": v2WriteOp("Retweet a tweet", true, idParam)},
		"/2/users/{id}/retweets/{source_tweet_id}": map[string]any{"delete": v2WriteOp("Undo a retweet", false, idParam, v2PathParam("source_tweet_id", "The retweeted tweet id."))},
		"/2/users/{id}/following": map[string]any{
			"get":  v2ListOp("Who a user follows", idParam),
			"post": v2WriteOp("Follow a user", true, idParam),
		},
		"/2/users/{id}/following/{target_id}":           map[string]any{"delete": v2WriteOp("Unfollow a user", false, idParam, v2PathParam("target_id", "The followed user id."))},
		"/2/tweets/{id}/retweeted_by":                   map[string]any{"get": v2ListOp("Users who retweeted a tweet", idParam)},
		"/2/tweets/{id}/liking_users":                   map[string]any{"get": v2ListOp("Users who liked a tweet", idParam)},
		"/2/users/{id}/liked_tweets":                    map[string]any{"get": v2ListOp("Tweets a user liked", idParam)},
		"/2/users/{id}/followers":                       map[string]any{"get": v2ListOp("A user's followers", idParam)},
		"/2/users/{id}/timelines/reverse_chronological": map[string]any{"get": v2ListOp("The account's home timeline", idParam)},
	}
}

// v2ListOp builds a paginated GET operation: v2Op plus the shared max_results/
// pagination_token query parameters.
func v2ListOp(summary string, pathParams ...map[string]any) map[string]any {
	page := []map[string]any{
		v2QueryParam("max_results", "Page size, 5-100 (default 10)."),
		v2QueryParam("pagination_token", "Cursor from a previous meta.next_token."),
	}
	return v2Op(summary, append(pathParams, page...)...)
}

// v2Components builds the reusable schema and security components.
func v2Components() map[string]any {
	obj := map[string]any{"type": "object", "additionalProperties": true}
	objArray := map[string]any{"type": "array", "items": obj}
	return map[string]any{
		"securitySchemes": map[string]any{
			"bearerAuth": map[string]any{"type": "http", "scheme": "bearer"},
		},
		"schemas": map[string]any{
			"Envelope": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"data":     map[string]any{"description": "A single object or an array of objects, depending on the endpoint."},
					"includes": map[string]any{"$ref": "#/components/schemas/Includes"},
					"meta":     map[string]any{"$ref": "#/components/schemas/Meta"},
					"errors":   map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/Error"}},
				},
			},
			"Includes": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"users": objArray, "tweets": objArray, "media": objArray,
					"polls": objArray, "places": objArray,
				},
			},
			"Meta": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"result_count": map[string]any{"type": "integer"},
					"next_token":   map[string]any{"type": "string"},
					"newest_id":    map[string]any{"type": "string"},
					"oldest_id":    map[string]any{"type": "string"},
				},
			},
			"Error": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"title":         map[string]any{"type": "string"},
					"detail":        map[string]any{"type": "string"},
					"type":          map[string]any{"type": "string"},
					"resource_type": map[string]any{"type": "string"},
					"resource_id":   map[string]any{"type": "string"},
					"parameter":     map[string]any{"type": "string"},
					"value":         map[string]any{"type": "string"},
				},
			},
		},
	}
}
